# Generated by Django 2.1 on 2018-08-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180814_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/<django.db.models.fields.CharField>_<django.db.models.fields.CharField>'),
        ),
    ]
